import path from "node:path";
import { assertValidRepository } from "./repository.mjs";

export async function buildCatalogs(root) {
  const repository = await assertValidRepository(root);
  const router = repository.skills.find((skill) => skill.name === "prosto-find");
  if (!router) return [];

  const referenceDirectory = path.join(router.directory, "references");
  return [
    {
      file: path.join(referenceDirectory, "catalog.md"),
      content: renderCatalog(repository, false),
    },
    {
      file: path.join(referenceDirectory, "catalog.internal.md"),
      content: renderCatalog(repository, true),
    },
  ];
}

export function renderCatalog(repository, includeInternal) {
  const skills = repository.skills
    .filter((skill) => includeInternal || skill.maturity === "stable")
    .sort((left, right) => left.name.localeCompare(right.name));
  const flows = repository.flows
    .filter((flow) => includeInternal || !flow.internal)
    .sort((left, right) => left.name.localeCompare(right.name));

  const lines = [
    "# Skill Catalog",
    "",
    "<!-- Generated by npm run generate. Do not edit. -->",
    "",
    includeInternal
      ? "Includes Stable, Experimental, and System Skills for Maintainer use."
      : "Includes Stable Skills and public Flows.",
    "",
    "## Skills",
    "",
  ];

  if (skills.length === 0) {
    lines.push("No Skills are available in this catalog.", "");
  } else {
    lines.push(
      "| Skill | Invocation | Maturity | Required Peers | Tags | Description |",
      "| --- | --- | --- | --- | --- | --- |",
    );
    for (const skill of skills) {
      lines.push(
        `| ${skill.name} | ${skill.invocation} | ${skill.maturity} | ${
          skill.requires.join(", ") || "—"
        } | ${skill.tags.join(", ")} | ${escapeCell(skill.description)} |`,
      );
    }
    lines.push("");
  }

  lines.push("## Flows", "");
  if (flows.length === 0) {
    lines.push("No Flows are available in this catalog.", "");
  } else {
    for (const flow of flows) {
      lines.push(`- **${flow.name}**: ${flow.description} (${flow.skills.join(" → ")})`);
    }
    lines.push("");
  }

  return `${lines.join("\n")}\n`;
}

function escapeCell(value) {
  return String(value).replaceAll("|", "\\|").replaceAll("\n", " ");
}
